import Link from "next/link";
import PageHero from "@/components/PageHero";
import CTA from "@/components/CTA";
import { aboutPillars, experience, institutionalExperience, images, selectedExperience } from "@/lib/content";

export default function AboutPage() {
  return <main>
    <PageHero eyebrow="ABOUT STEMENABLED" title="A practical STEM transformation partner for schools." description="STEMEnabled helps schools connect infrastructure, educator capability, curriculum and hands-on technology programmes into a coherent STEM ecosystem." />
    <section className="section"><div className="container split-feature"><div><span className="eyebrow">WHO WE ARE</span><h2>Built around practical STEM education.</h2><p>STEMEnabled is an education and technology consultancy based in Lagos, Nigeria. We work with schools that want to move beyond conventional ICT and create environments where students can use technology to solve problems, build products and develop confidence as creators.</p><p>Our work is grounded in more than a decade of STEM education, robotics, physical computing, curriculum development and educator training experience.</p></div><div className="feature-image" style={{backgroundImage:`url(${images.teacher})`}} /></div></section>
    <section className="section section-soft"><div className="container"><div className="section-head center"><span className="eyebrow">OUR APPROACH</span><h2>Four principles shape the work.</h2></div><div className="impact-grid">{aboutPillars.map(([title,text])=><div className="impact" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">FOUNDATION OF EXPERIENCE</span><h2>Experience that informs the STEMEnabled model.</h2><p>STEMEnabled draws on the founder's documented professional experience. These credentials describe the experience behind the company and are not presented as a list of STEMEnabled client projects.</p></div><div className="credential-grid">{experience.map(([a,b])=><div className="credential" key={a}><b>{a}</b><span>{b}</span></div>)}</div></div></section>
    <section className="section section-dark"><div className="container"><div className="section-head"><span className="eyebrow">SELECTED EXPERIENCE</span><h2>Capability built through years of delivery.</h2></div><div className="case-grid">{selectedExperience.map(([title,text])=><div className="case" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><p className="small-dark">Experience includes work and programme delivery associated with STEMCafe, The Creative Kids Zone, Arynx and Swiftberry, alongside educational collaborations and facilitation in Nigeria and Ghana.</p></div></section>
    <section className="section"><div className="container"><div className="section-head center"><span className="eyebrow">ECOSYSTEM EXPERIENCE</span><h2>Organisations and institutions connected to the founder's professional journey.</h2></div><div className="tag-cloud">{institutionalExperience.map(x=><span key={x}>{x}</span>)}</div><p className="disclaimer">These names represent documented experience, collaboration or programme exposure. They are not all STEMEnabled clients or current partners.</p></div></section>
    <section className="section section-soft"><div className="container center-block"><span className="eyebrow">READY TO WORK TOGETHER?</span><h2>Let's design the right STEM pathway for your school.</h2><Link className="btn btn-primary" href="/assessment">Book a STEM Needs Assessment</Link></div></section><CTA />
  </main>;
}
